module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-400": "var(--gray-400)",
        "gray-50": "var(--gray-50)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-800": "var(--gray-800)",
        "gray-900": "var(--gray-900)",
        "gray-900-default": "var(--gray-900-default)",
        graywhite: "var(--graywhite)",
        "primary-50": "var(--primary-50)",
        "primary-60-0default": "var(--primary-60-0default)",
        "primary-900": "var(--primary-900)",
        "secondary-300": "var(--secondary-300)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-large-400": "var(--body-large-400-font-family)",
        "body-large-500": "var(--body-large-500-font-family)",
        "body-regular-400": "var(--body-regular-400-font-family)",
        "body-regular-500": "var(--body-regular-500-font-family)",
        "body-regular-600": "var(--body-regular-600-font-family)",
        "body-small-400": "var(--body-small-400-font-family)",
        "heading-01": "var(--heading-01-font-family)",
        "heading-02": "var(--heading-02-font-family)",
        "heading-03": "var(--heading-03-font-family)",
        "heading-04": "var(--heading-04-font-family)",
        "heading-05": "var(--heading-05-font-family)",
        "text-md-regular": "var(--text-md-regular-font-family)",
        "text-sm-bold": "var(--text-sm-bold-font-family)",
        "text-sm-regular": "var(--text-sm-regular-font-family)",
        "text-xl-bold": "var(--text-xl-bold-font-family)",
        "text-xl-regular": "var(--text-xl-regular-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "shadow-01": "var(--shadow-01)",
        "shadow-04": "var(--shadow-04)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
